### ISSUE TITLE
Should be allowed to have multiple OIDC issuers

### ISSUE THREAD

**Issue by pheyvaer** [solid/access-token-verifier#11] opened 2021-11-02 11:00 UTC
I get this error when my WebID has two OIDC issuers
```
warn: Error verifying WebID via DPoP-bound access token: The access token issuer doesn't match its associated WebID's trusted OIDC issuers.
```

**Comment by RubenVerborgh** [comment] 2021-11-23 22:15
@pheyvaer Can't rep at the moment because your profile seems to have changed: https://rdf-play.rubensworks.net/#url=https%3A%2F%2Fpieterheyvaert.com%2F%23me

**Comment by RubenVerborgh** [comment] 2021-11-23 22:16
(Note that there is a 60 second delay, that might have been the issue: #12)

**Comment by pheyvaer** [comment] 2021-11-24 06:28
Yes I changed it, because I couldn't be blocked by this. But you can easily replicate by just adding a two issuers in a test WebID though.

**Comment by RubenVerborgh** [comment] 2021-12-02 14:09
@pheyvaer I tried reproducing with https://multiruben.solidcommunity.net/profile/card:

```turtle
:me solid:oidcIssuer <https://example.com>, <https://solidcommunity.net>, <https://example.org>.
```

but it works:

```
2021-12-02T14:07:49.937Z [DPoPWebIdExtractor] info: Verified WebID via DPoP-bound access token: https://multiruben.solidcommunity.net/profile/card#me
```

**Comment by matthieubosquet** [comment] 2022-01-10 22:52
@pheyvaer have you been able to reproduce?
If not, I will close the issue.

**Comment by pheyvaer** [comment] 2022-01-11 06:02
It's fine to close this 🙂

**Closed** 2022-01-11 09:52 UTC
